export function buildErrorType(): string {
  return [
    "import Foundation",
    "",
    "enum NetworkError: Error, LocalizedError {",
    "    case invalidURL",
    "    case httpError(statusCode: Int, payload: Data?)",
    "    case decodingError(Error)",
    "    case networkFailure(Error)",
    "    case unknown",
    "",
    "    var errorDescription: String? {",
    "        switch self {",
    "        case .invalidURL:",
    "            return \"The URL is invalid.\"",
    "        case .httpError(let statusCode, _):",
    "            return \"Unexpected HTTP status code: \\(statusCode).\"",
    "        case .decodingError(let error):",
    "            return \"Failed to decode response: \\(error.localizedDescription)\"",
    "        case .networkFailure(let error):",
    "            return \"Network request failed: \\(error.localizedDescription)\"",
    "        case .unknown:",
    "            return \"An unknown networking error occurred.\"",
    "        }",
    "    }",
    "}",
  ].join("\n");
}
