import {
  Brain, FileText, FileCode, Trash2, Terminal, Package, Server,
  RefreshCw, Database, GitBranch, Globe, Camera, Monitor, Eye,
  ScrollText, Zap, Link, Lock, Bug, FlaskConical, Activity,
  Search, Key, FilePlus, TerminalSquare,
} from "lucide-react";

export type AnimationStyle = "spin" | "pulse" | "bounce" | "flash" | "ping" | "shake";

export const TOOL_ICON_MAP: Record<string, React.ElementType> = {
  "analysis.think":     Brain,
  "file.read":          FileText,
  "file.write":         FileCode,
  "file.delete":        Trash2,
  "console.run":        Terminal,
  "package.install":    Package,
  "package.remove":     Package,
  "server.start":       Server,
  "server.restart":     RefreshCw,
  "db.push":            Database,
  "db.migrate":         Database,
  "git.clone":          GitBranch,
  "git.commit":         GitBranch,
  "deploy.publish":     Globe,
  "screenshot.capture": Camera,
  "ui.render":          Monitor,
  "preview.open":       Eye,
  "logs.stream":        ScrollText,
  "api.call":           Link,
  "auth.login":         Lock,
  "webhook.trigger":    Zap,
  "debug.run":          Bug,
  "test.run":           FlaskConical,
  "monitor.check":      Activity,
  "search.web":         Search,
  "search.code":        Search,
  "env.read":           Key,
  "env.write":          Key,
  "shell.exec":         TerminalSquare,
  "file.create":        FilePlus,
};

export const TOOL_COLOR_MAP: Record<string, string> = {
  "analysis.think":     "#a78bfa",
  "file.read":          "#7dd3fc",
  "file.write":         "#86efac",
  "file.delete":        "#f87171",
  "console.run":        "#fbbf24",
  "package.install":    "#fb923c",
  "package.remove":     "#fb923c",
  "server.start":       "#4ade80",
  "server.restart":     "#fb923c",
  "db.push":            "#34d399",
  "db.migrate":         "#34d399",
  "git.clone":          "#86efac",
  "git.commit":         "#86efac",
  "deploy.publish":     "#60a5fa",
  "screenshot.capture": "#f472b6",
  "ui.render":          "#c084fc",
  "preview.open":       "#f472b6",
  "logs.stream":        "#94a3b8",
  "api.call":           "#38bdf8",
  "auth.login":         "#facc15",
  "webhook.trigger":    "#818cf8",
  "debug.run":          "#f87171",
  "test.run":           "#34d399",
  "monitor.check":      "#a78bfa",
  "search.web":         "#f97316",
  "search.code":        "#22d3ee",
  "env.read":           "#facc15",
  "env.write":          "#fbbf24",
  "shell.exec":         "#a3e635",
  "file.create":        "#86efac",
};

export const TOOL_EMOJI_MAP: Record<string, string> = {
  "analysis.think":     "🧠",
  "file.read":          "📁",
  "file.write":         "📁",
  "file.delete":        "📁",
  "console.run":        "💻",
  "package.install":    "📦",
  "package.remove":     "📦",
  "server.start":       "🟢",
  "server.restart":     "🔄",
  "db.push":            "🗄️",
  "db.migrate":         "🗄️",
  "git.clone":          "🌿",
  "git.commit":         "🌿",
  "deploy.publish":     "🚀",
  "screenshot.capture": "📸",
  "ui.render":          "🖥️",
  "preview.open":       "👁️",
  "logs.stream":        "📜",
  "api.call":           "🔗",
  "auth.login":         "🔐",
  "webhook.trigger":    "📡",
  "search.web":         "🔍",
  "search.code":        "🔎",
  "env.read":           "🔑",
  "env.write":          "🔑",
  "shell.exec":         "⚡",
  "file.create":        "📄",
};

export const TOOL_ANIMATION_MAP: Record<string, AnimationStyle> = {
  "analysis.think":     "pulse",
  "file.read":          "bounce",
  "file.write":         "bounce",
  "file.delete":        "shake",
  "console.run":        "flash",
  "package.install":    "spin",
  "package.remove":     "spin",
  "server.start":       "pulse",
  "server.restart":     "spin",
  "db.push":            "ping",
  "db.migrate":         "ping",
  "git.clone":          "spin",
  "git.commit":         "pulse",
  "deploy.publish":     "bounce",
  "screenshot.capture": "flash",
  "ui.render":          "pulse",
  "preview.open":       "flash",
  "logs.stream":        "pulse",
  "api.call":           "ping",
  "auth.login":         "pulse",
  "webhook.trigger":    "flash",
  "debug.run":          "shake",
  "test.run":           "ping",
  "monitor.check":      "pulse",
  "search.web":         "spin",
  "search.code":        "spin",
  "env.read":           "flash",
  "env.write":          "flash",
  "shell.exec":         "flash",
  "file.create":        "bounce",
};
